version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: snackmaster-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: snackmaster
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: snackmaster-server
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  client:
    build: ./client
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - server

volumes:
  mongo-data: