name: CI

on:
  push:
  pull_request:

jobs:
  server:
    name: Server CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & test server
        working-directory: server
        run: |
          npm ci
          npm run lint
          npm test

  client:
    name: Client CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & build client
        working-directory: client
        run: |
          npm ci
          npm run lint || true
          npm run build || true